### ISSUE TITLE
Ch 01-Q4

### ISSUE THREAD

**Issue by IEH-tekmexico** [shardool/JavaScript_Assignment_1#1]
What sort of testing should we do on JavaScript code before deployment?
  - Constructive and destructive techniques are debugging techniques, used when trying to determine where the root cause of an error lies. Types of testing would include functionality, performance, and compatibility testing. If errors are detected, then we proceed with constructive or destructive testing.

**Comment by shardool** [comment]
Thanks for pointing this out Ivan. I have corrected my answer now, therefore I request you to review and close this issue. Even as I was typing my answer I was not fully convinced about it, but I figured you'd be looking for what the Ninja Books says. In particular, I was influenced by the following lines from that book. My bad, as I misinterpreted it.
![question](https://cloud.githubusercontent.com/assets/5981515/10187361/a18b961e-6775-11e5-8259-2831ae882227.png)
