### ISSUE TITLE
Ch6 - Q6: Is it possible for an object to inherit behavior from another? If so, how?

### ISSUE THREAD

**Issue by IEH-tekmexico** [shardool/JavaScript_Assignment_1#11]
On the listing, when invoking the parent's implementation of _**sayHi**_, it would be best to not create a new instance for just the method invocation. An alternate implementation:
```javascript
Child.prototype.sayHi = (function (){
    var superHi = Child.prototype.sayHi;
    return function(){
      console.log('overridden hi from inherited object (Parent)');
      //new this.constructor().sayHi();
      superHi();
    };
})();
```

Had the method been declared in the parent's prototype instead of the constructor, the parent's implementation could have been accessed through the prototype chain.

**Comment by shardool** [comment]
Made the suggested change. However, since the "sayHi" method on the parent Object was "added" in the constructor in my earlier listing (instead of "attaching" it to the parent's prototype), I had resorted to creating a new instance of the Parent Object just to invoke it's implementation of the sayHi method. Kindly review and close this issue.

**Comment by IEH-tekmexico** [comment]
The new changes now cause the function to be infinitely recursive. Please fix the issue. 
```javascript
var Parent = function Parent(){};
Parent.prototype.sayHi = function(){
                    console.log('hi from Parent');
                };
var Child = function Child(){};
Child.prototype = new Parent();
Child.prototype.sayHi = function(){
   var superHi = Child.prototype.sayHi; // <- *the problem is here*
    console.log('overridden hi from inherited object');
    superHi();
};
var c = new Child();
c.sayHi()
```

**Comment by shardool** [comment]
//Corrected the code in the listing to the following. Kindly review 
var Parent = function Parent(){};
Parent.prototype.sayHi = function(){
                    console.log('hi from Parent');
                };
var Child = function Child(){};
Child.prototype = new Parent();
Child.prototype.sayHi = function(){
    console.log('overridden hi from inherited object');
    this.constructor.prototype.sayHi(); // calls Parent's implementation of the method. 
};
var c = new Child();
c.sayHi()
