### ISSUE TITLE
Ch 07 - Q7: What are captures?

### ISSUE THREAD

**Issue by IEH-tekmexico** [shardool/JavaScript_Assignment_1#13]
The definition given is that of a backreference. A capture is a submatch. These submatches may be returned as the result of the regular expression execution (i.e. match or exec) as well as be used as part of the match at a later point in the pattern. When referenced at a later point (through \1, \2, etc) they are backreferences to a capture.

**Comment by shardool** [comment]
updated my answer with the following. Please review and close. 
A capture is a subexpression. These subexpressions are created by enclosing a bunch of characters inside a pair of parantheses, which is referred to as "capturing-group". By default, the capturing groups are "active-subexpressions" and maybe accessed at a later point in the same expression by back-referencing, using \1,\2 and so on. Also, in the String.prototype.replace() method, where the second parameter is the replacement-string, we can reference the capturing group using $1,$2 and so on.If we wish to make a subexpression passive, we need to include "?:" inside the parantheses, right after the opening paranthesis which effectively makes it a non-capturing group
