### ISSUE TITLE
Ch 03-Q2

### ISSUE THREAD

**Issue by IEH-tekmexico** [shardool/JavaScript_Assignment_1#3]
How are they (functions) declared?
  Answered with "Lorem ipsum dolor sit amet, ..."?

**Comment by shardool** [comment]
Apologies for pushing the "Lorem Ipsum" text that my Emmet plugin put out, when I just wanted to format the answer and not actually answer it at that moment. Now I have my answer there. Please review and close the issue.

**Comment by IEH-tekmexico** [comment]
It is also possible to declare them using a constructor. Example:

var bar = new Function("a,b","return a+b"); 
/*
Somewhat equivalent to function(a,b){ return a+b;}
*/

I don't think the book has mentioned this method at this early chapter, but I just wanted to point it out.

**Comment by shardool** [comment]
thanks Ivan :+1:
