### ISSUE TITLE
Ch 04-Q10: How can it (memoization) be implemented in JavaScript?

### ISSUE THREAD

**Issue by IEH-tekmexico** [shardool/JavaScript_Assignment_1#7]
The code given does not exemplify memoization. The point is to ensure that previously computed values are not recalculated if the task is expensive. The way to implement it is to store previously computed values and use the parameters that lead to those values as a key. In the example, whole functions are stored in a cache, but not their computed values.

**Comment by shardool** [comment]
corrected it

**Comment by IEH-tekmexico** [comment]
The function given in the example does not make use of memoization and the output shows it. When a match is found in the function's cache, it will display a message that it found the answer in the cache but after that it will still go ahead and calculate the value. The last 4 lines of the log show the error:

fetching from cache : 10 : false 
fresh compute : 10 : false 
fetching from cache : 11 : true 
fresh compute : 11 : true

**Comment by shardool** [comment]
had forgotten to "return" from the if block after fetching it from the cache. Now I have included a return statement. Please review and close. Thanks
