### ISSUE TITLE
Ch 05 - Q8: What are immediate functions?

### ISSUE THREAD

**Issue by IEH-tekmexico** [shardool/JavaScript_Assignment_1#8]
The answer needs some clarification:

> IIFE, also known as Immediately Invoked Funtion Expression, is a self-executing anonymous function [sic]

_Immediately invoked_ and _self-executing_ are not great definitions for each other. They are anonymous functions that are executed as soon as they are declared, directly from their definition. They are not stored for future execution. Example:
    
    (function(){ 
        /* logic goes here */
    })();

> ... which is always ready with the result of executing the function even while the function itself has returned and gone out of scope. 

An immediately executed function need not return any value.

> We can make this IIFE return a function that wrap the local variables and paramets inside the closure.[sic]

This part is tangential to the question being asked, and a little lacking as an example. A better followup to the definition would be to list a few uses of immediate functions, without going into too much detail. Example:
 * Encapsulating logic
 * creating scopes, compensating for lack of block scope in JS
 * Initializing private values to be used on a public function/object

**Comment by shardool** [comment]
Thanks Ivan,
I have amended my answer now.
Also, included the line, to clarify that we can **optionally** make the IIFE return a function that creates a closure around the local variables and parameters of the outer function.
"We can **optionally** make the IIFE return a function that wraps the local variables and parameters inside the closure.* "
Please review and close the issue
